# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bg-stats' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bg-stats
  pod ‘FMDB’

  target 'bg-statsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bg-statsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
